spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: as741023##

#  thymeleaf:
#    prefix: classpath:/templates
#    suffix: .html
#    mode: LEGACYHTML5
#    check-template-location: true


  jpa:
    hibernate:
      use-new-id-generator-mappings: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: kok1434@gmail.com
    password: as741023##
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enalble: true
            required: true
          validTime : 5000

#  mvc:
#    static-path-pattern: /static/**

server:
  port: 8080

jwt:
  secret:
    signature: "SEOKYOCHEOL"

hendisantika:
  app:
    jwtSecret: "jwtSecretKey"
    jwtExpiration: 86400



